datagraph/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from django.views.decorators.csrf import csrf_exempt

from graphene_django.views import GraphQLView
from datagraph.schema import schema

from viewer import urls as viewer_url
from viewer.forms import DataGraphAuthenticationForm
from engine import urls as engine_url


urlpatterns = [
    path('accounts/login/', auth_views.LoginView.as_view(
        authentication_form=DataGraphAuthenticationForm), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('admin', admin.site.urls),
    path('graphql', csrf_exempt(GraphQLView.as_view(graphiql=True, schema=schema))),
    path('engine/', include(engine_url)),
    re_path('djga/', include('google_analytics.urls')),
    path('', include(viewer_url)),
]

engine/urls.py
from django.urls import path
from . import views

app_name = 'engine'
urlpatterns = [
    path('', views.workbench, name='workbench'),
    path(
        'vega-spec/<uuid:node_id>/',
        views.vega_spec,
        name='vega-spec'),
    path(
        'node-editor/<uuid:node_id>/',
        views.existing_node_editor,
        name='existing-node-editor'),
    path(
        'node-editor/<slug:node_type>/<slug:node_name>/',
        views.new_node_editor,
        name='new-source-node-editor'),
    path(
        'node-editor/<slug:node_type>/<slug:node_name>/<uuid:source_id>',
        views.new_node_editor,
        name='new-node-editor'
    ),
    path(
        'node-editor/<uuid:node_id>/delete',
        views.delete_node,
        name='node-editor-deletion'
    )
]

engine/calculator/forms.py
from django import forms

from engine.forms import CalculatorForm
from graph.models import DataNode


class RollingForm(CalculatorForm):

    window = forms.IntegerField(
        label='Window',
        widget=forms.NumberInput(attrs={'class': 'form-control'}))

    @classmethod
    def load_special_fields(cls, node: DataNode):
        fields = super().load_special_fields(node)
        fields.update({
            'window': node.params.get('window', 1) if node.params else 1
        })
        return fields

    def save_special_fields(self, node: DataNode):
        super().save_special_fields(node)
        node.params = {
            'window': self.cleaned_data['window']
        }
        node.save()

engine/forms.py
from django import forms
from django.core.exceptions import ValidationError

from graph.models import DataNode, DataEdge
from graph.queries import (
    get_units, get_data_readers, get_data_nodes_by_dest,
    set_data_node_sources, link_data_nodes, get_data_node_by_id,
    get_all_data_nodes)


class DataNodeUnitChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.name


class DataNodeModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.title


class DataNodeModelMultipleChoiceField(forms.ModelMultipleChoiceField):
    def label_from_instance(self, obj):
        return obj.title


class DataReadersForm(forms.Form):
    source_nodes = DataNodeModelMultipleChoiceField(
        queryset=get_data_readers(),
        required=False,
        to_field_name='id',
        widget=forms.SelectMultiple(
            attrs={
                'id': 'data-sources-picker',
                'class': 'form-control selectpicker',
                'data-live-search': 'true',
                'data-max-options': '3',
            }
        ))


class ComponentForm(forms.Form):
    id = forms.UUIDField(
        widget=forms.HiddenInput(), required=False)
    title = forms.CharField(
        label='Title', max_length=128,
        widget=forms.TextInput(attrs={'class': 'form-control'}))
    name = forms.CharField(
        label='Name', max_length=128,
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'readonly': True}))
    type = forms.CharField(
        label='Type', max_length=20,
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'readonly': True}))
    public = forms.BooleanField(
        label='Public', initial=True, required=False)
    unit = DataNodeUnitChoiceField(
        queryset=get_units(),
        required=False,
        to_field_name='name',
        label='Unit',
        widget=forms.Select(
            attrs={'class': 'form-control selectpicker'}
        ))

    @classmethod
    def load_from_node(cls, node: DataNode):
        form_args = {
            'id': node.id,
            'title': node.title,
            'name': node.name,
            'type': node.type,
            'public': node.public,
            'unit': node.unit
        }
        form_args.update(
            cls.load_special_fields(node)
        )
        return cls(form_args)

    @staticmethod
    def load_special_fields(node: DataNode):
        return {}

    def save_to_node(self):
        if self.is_valid():
            node_id = self.cleaned_data.get('id')
            if node_id is not None:
                node = get_data_node_by_id(node_id)
                node.type = self.cleaned_data['type']
                node.name = self.cleaned_data['name']
                node.title = self.cleaned_data['title']
                node.public = self.cleaned_data['public']
                node.unit = self.cleaned_data['unit']
            else:
                node = DataNode(
                    type=self.cleaned_data['type'],
                    name=self.cleaned_data['name'],
                    title=self.cleaned_data['title'],
                    public=self.cleaned_data['public'],
                    unit=self.cleaned_data['unit']
                )
            self.save_special_fields(node)
            node.save()
            return node.id
        return None

    def save_special_fields(self, node: DataNode):
        pass


class CalculatorForm(ComponentForm):
    source_node = DataNodeModelChoiceField(
        queryset=get_all_data_nodes(),
        to_field_name='id',
        widget=forms.Select(
            attrs={
                'class': 'form-control selectpicker',
                'data-live-search': 'true',
            }
        ))

    @classmethod
    def load_special_fields(cls, node: DataNode):
        fields = super().load_special_fields(node)
        edge = DataEdge.objects.get(dest_id=node.id)
        fields.update({'source_node': edge.source})
        return fields

    def save_special_fields(self, node: DataNode):
        super().save_special_fields(node)
        node.save()

        source = self.cleaned_data['source_node']
        link_data_nodes(source, node)


class AggregatorForm(ComponentForm):
    source_nodes = DataNodeModelMultipleChoiceField(
        queryset=DataNode.objects.all(),
        to_field_name='id',
        widget=forms.SelectMultiple(
            attrs={
                'class': 'form-control selectpicker',
                'data-live-search': 'true',
            }
        ))

    @classmethod
    def load_special_fields(cls, node: DataNode):
        fields = super().load_special_fields(node)
        nodes = get_data_nodes_by_dest(node.id)
        fields.update({'source_nodes': nodes})
        return fields

    def save_special_fields(self, node: DataNode):
        super().save_special_fields(node)
        node.save()

        source_nodes = self.cleaned_data['source_nodes']
        set_data_node_sources(source_nodes, node)

    def clean_source_nodes(self):
        source_nodes = self.cleaned_data['source_nodes']
        if len(source_nodes) < 2:
            raise ValidationError('Must select at least 2 source nodes')
        return source_nodes


class WriterForm(CalculatorForm):
    pass

engine/views.py
import importlib

from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views.decorators.cache import cache_page

from graph.models import DataNode, DataNodeType
from graph.queries import get_data_node_by_id, get_data_nodes_by_ids
from engine.component import Component
from engine.forms import DataReadersForm
from engine.queries import is_node_deletable, get_vega_spec_writers


@login_required
def workbench(request):
    node_ids = request.session.get('source_node_ids', set())
    if node_ids:
        source_nodes = get_data_nodes_by_ids(node_ids)
        form = DataReadersForm({'source_nodes': source_nodes})
    else:
        form = DataReadersForm()
    return render(
        request, 'engine/workbench.html',
        {
            'active_menu': 'workbench',
            'form': form
        })


@login_required
def new_node_editor(
        request,
        node_type: str,
        node_name: str,
        source_id: str = None):
    py_node_name = node_name.replace('-', '_')

    module_name = 'engine.{type}.{name}'.format(
        type=node_type,
        name=py_node_name)
    module = importlib.import_module(module_name)
    form_class = getattr(module, 'Form')

    if request.method == 'POST':
        form = form_class(request.POST)
        if form.is_valid():
            node_id = form.save_to_node()
            if node_type == DataNodeType.READER.value.lower():
                request.session['source_nodes'] = request.session.get('source_nodes', set())
                request.session['source_nodes'].add(node_id)
            messages.success(request, 'Node has been saved.')
            return HttpResponseRedirect(reverse('engine:workbench'))
    else:
        form_fields = {
            'type': node_type.upper(),
            'name': py_node_name
        }
        if source_id:
            if node_type == 'aggregator':
                form_fields.update({
                    'source_nodes': [get_data_node_by_id(source_id)]
                })
            else:
                form_fields.update({
                    'source_node': get_data_node_by_id(source_id)
                })
        form = form_class(initial=form_fields)

    return render(
        request,
        'engine/node_editor.html',
        {
            'active_menu': 'workbench',
            'form': form
        }
    )


@login_required
def existing_node_editor(request, node_id: str):
    node = get_object_or_404(DataNode, id=node_id)
    form_class = Component.get_form_class(node)

    if request.method == 'POST':
        form = form_class(request.POST)
        if form.is_valid():
            form.save_to_node()
            messages.success(request, 'Node has been saved.')
            return HttpResponseRedirect(reverse('engine:workbench'))
    else:
        form = form_class.load_from_node(node)

    return render(
        request,
        'engine/node_editor.html',
        {
            'active_menu': 'workbench',
            'node_id': node_id,
            'form': form
        }
    )


@login_required
def delete_node(request, node_id: str):
    node = get_object_or_404(DataNode, id=node_id)
    if is_node_deletable(node_id):
        node.delete()
        messages.success(request, 'Node has been deleted.')
        return HttpResponseRedirect(reverse('engine:workbench'))
    messages.error(request, 'Node cannot be deleted.')
    return HttpResponseRedirect(
        reverse('engine:existing-node-editor', kwargs={'node_id': node_id}))


@cache_page(86400)
def vega_spec(request, node_id: str):
    """This view generates vega visualization specification"""
    data_node = get_object_or_404(
        get_vega_spec_writers(not request.user.is_authenticated),
        id=node_id)
    data_component = Component.get_component(data_node)

    return HttpResponse(
        data_component.process(),
        content_type='application/json')

engine/templates/engine/node_editor.html
{% extends "base-sb-admin-2.html" %}

{% load static %}

{% block title %}
    Data Graph - Node Editor
{% endblock %}

{% block page_content %}
    <div class="container-fluid">
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Node Editor</h1>
        </div>
        <div class="col-md-8">
            <form method="POST" role="form">
                {% csrf_token %}
                {{ form.non_field_errors }}
                {% for field in form.hidden_fields %}
                    <div class="fieldWrapper form-group">
                        {{ field }}
                    </div>
                {% endfor %}

                {% for field in form.visible_fields %}
                    <div class="fieldWrapper form-group">
                        {{ field.label_tag }}
                        {{ field }}
                        {% if field.help_text %}
                            <p class="help">{{ field.help_text|safe }}</p>
                        {% endif %}
                        {{ field.errors }}
                    </div>
                {% endfor %}
                <input type="submit" class="btn btn-primary mb-2" value="Submit" />
                <a class="btn btn-secondary mb-2" href="{% url 'engine:workbench' %}" role="button">Back</a>
                {% if node_id %}
                    <a class="btn btn-danger mb-2 float-right" href="{% url 'engine:node-editor-deletion' node_id %}" role="button">Delete</a>
                {% endif %}
            </form>
        </div>
    </div>
{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static "bootstrap-select/css/bootstrap-select.min.css" %}">
    <link rel="stylesheet" href="{% static "jsuits/css/jsuites.css" %}" type="text/css" />
    <link rel="stylesheet" href="{% static "jexcel/css/jexcel.css" %}" type="text/css" />
{% endblock %}

{% block extra_js %}
    <script src="{% static "bootstrap-select/js/bootstrap-select.min.js" %}"></script>
    <script src="{% static "jexcel/js/jexcel.js" %}" crossorigin="anonymous"></script>
    <script src="{% static "jsuits/js/jsuites.js" %}" crossorigin="anonymous"></script>
    <script src="{% static "datagraph/engine-spreadsheet-widget.bundle.js" %}" crossorigin="anonymous"></script>
    <script src="{% static "datagraph/engine-node-editor.bundle.js" %}" crossorigin="anonymous"></script>
{% endblock %}

engine/templates/engine/workbench.html
{% extends "base-sb-admin-2.html" %}

{% load static %}

{% block title %}
    Data Graph - Workbench
{% endblock %}

{% block page_content %}
    <div class="container-fluid">
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Workbench</h1>
        </div>
        <div class="row">
            <div class="col">
                <form method="post">
                    {% csrf_token %}
                    <div class="input-group">
                        {{ form.source_nodes }}
                        <div class="input-group-append">
                            <button class="btn btn-secondary" type="button" id="data-sources-reset">
                                <i class="fas fa-trash fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col">
                {% if user.is_authenticated %}
                    <div class="btn-group ml-2">
                        <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-plus fa-sm"></i>
                        </button>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'engine:new-source-node-editor' 'reader' 'rba' %}">Reserve Bank of Australia</a>
                            <a class="dropdown-item" href="{% url 'engine:new-source-node-editor' 'reader' 'fred' %}">Federal Reserve Bank of St.Louis</a>
                            <a class="dropdown-item" href="{% url 'engine:new-source-node-editor' 'reader' 'manual' %}">Manual</a>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="col-12" id="graph-container"></div>
        </div>
            {% if user.is_authenticated %}
                <div class="dropdown-menu" id="data-graph-context-menu">
                    <a class="dropdown-item" href="{% url 'engine:existing-node-editor' '00000000-0000-0000-0000-000000000000' %}">Edit</a>
                    <h6 class="dropdown-header">Link a Calculator</h6>
                    <a class="dropdown-item" href="{% url 'engine:new-node-editor' 'calculator' 'col_rename' '00000000-0000-0000-0000-000000000000' %}">Column Rename</a>
                    <a class="dropdown-item" href="{% url 'engine:new-node-editor' 'calculator' 'col_sel' '00000000-0000-0000-0000-000000000000' %}">Column Selection</a>
                    <a class="dropdown-item" href="{% url 'engine:new-node-editor' 'calculator' 'drop_na' '00000000-0000-0000-0000-000000000000' %}">Drop N/A</a>
                    <a class="dropdown-item" href="{% url 'engine:new-node-editor' 'calculator' 'pct_change' '00000000-0000-0000-0000-000000000000' %}">Percent Change</a>
                    <a class="dropdown-item" href="{% url 'engine:new-node-editor' 'calculator' 'add' '00000000-0000-0000-0000-000000000000' %}">Addition</a>
                    <a class="dropdown-item" href="{% url 'engine:new-node-editor' 'calculator' 'mul' '00000000-0000-0000-0000-000000000000' %}">Multiplication</a>
                    <a class="dropdown-item" href="{% url 'engine:new-node-editor' 'calculator' 'rolling_sum' '00000000-0000-0000-0000-000000000000' %}">Rolling Sum</a>
                    <a class="dropdown-item" href="{% url 'engine:new-node-editor' 'calculator' 'rolling_mul' '00000000-0000-0000-0000-000000000000' %}">Rolling Multiplication</a>
                    <h6 class="dropdown-header">Link a Aggregator</h6>
                    <a class="dropdown-item" href="{% url 'engine:new-node-editor' 'aggregator' 'concat' '00000000-0000-0000-0000-000000000000' %}">Concat</a>
                    <a class="dropdown-item" href="{% url 'engine:new-node-editor' 'aggregator' 'percent' '00000000-0000-0000-0000-000000000000' %}">Percent</a>
                    <h6 class="dropdown-header">Link a Vega Chart Spec</h6>
                    <a class="dropdown-item" href="{% url 'engine:new-node-editor' 'writer' 'vega_line' '00000000-0000-0000-0000-000000000000' %}">Line</a>
                    <a class="dropdown-item" href="{% url 'engine:new-node-editor' 'writer' 'vega_stacked_area' '00000000-0000-0000-0000-000000000000' %}">Stacked Area</a>
                    <a class="dropdown-item" href="{% url 'engine:new-node-editor' 'writer' 'vega_norm_stacked_area' '00000000-0000-0000-0000-000000000000' %}">Normalized Stacked Area</a>
                </div>
            {% endif %}
        <br/>
    </div>
{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static "bootstrap-select/css/bootstrap-select.min.css" %}">
{% endblock %}

{% block extra_js %}
    <script src="{% static "bootstrap-select/js/bootstrap-select.min.js" %}"></script>
    <script src="{% static "datagraph/engine-workbench.bundle.js" %}"></script>
{% endblock %}