datagraph/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from django.views.decorators.csrf import csrf_exempt

from graphene_django.views import GraphQLView
from datagraph.schema import schema

from viewer import urls as viewer_url
from viewer.forms import DataGraphAuthenticationForm
from engine import urls as engine_url


urlpatterns = [
    path('accounts/login/', auth_views.LoginView.as_view(
        authentication_form=DataGraphAuthenticationForm), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('admin', admin.site.urls),
    path('graphql', csrf_exempt(GraphQLView.as_view(graphiql=True, schema=schema))),
    path('engine/', include(engine_url)),
    re_path('djga/', include('google_analytics.urls')),
    path('', include(viewer_url)),
]

engine/urls.py
from django.urls import path
from . import views

app_name = 'engine'
urlpatterns = [
    path('', views.workbench, name='workbench'),
    path(
        'vega-spec/<uuid:node_id>/',
        views.vega_spec,
        name='vega-spec'),
    path(
        'node-editor/<uuid:node_id>/',
        views.existing_node_editor,
        name='existing-node-editor'),
    path(
        'node-editor/<slug:node_type>/<slug:node_name>/',
        views.new_node_editor,
        name='new-source-node-editor'),
    path(
        'node-editor/<slug:node_type>/<slug:node_name>/<uuid:source_id>',
        views.new_node_editor,
        name='new-node-editor'
    ),
    path(
        'node-editor/<uuid:node_id>/delete',
        views.delete_node,
        name='node-editor-deletion'
    )
]

viewer/urls.py
from django.urls import path
from . import views

app_name = 'viewer'
urlpatterns = [
    path('', views.index, name='index'),
    path('browser', views.browser, name='browser')
]

templates/base-sb-admin-2.html
{% load static %}
{% load google_analytics_tags %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="This website is dedicated to collect and share useful data by using data graph pipe">
        <meta name="keywords" content="Visualisation, Economy, DataGraph, Charts">
        <meta name="author" content="Wei Zheng">
        <title>{% block title %}Data Graph{% endblock %}</title>
        <link href="{% static "fontawesome/css/all.min.css" %}" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
        {% block extra_css %}
            {# Override this in templates to add extra stylesheets #}
        {% endblock %}
    </head>
    <body id="page-top">
        <!-- Page Wrapper -->
        <div id="wrapper">
            <!-- Sidebar -->
            <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

                <!-- Sidebar - Brand -->
                <li>
                    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'viewer:index' %}">
                        <div class="sidebar-brand-icon rotate-n-15">
                            <i class="fas fa-laugh-wink"></i>
                        </div>
                        <div class="sidebar-brand-text mx-3">Data Graph <sup>2</sup></div>
                    </a>
                </li>

                <!-- Divider -->
                <li>
                    <hr class="sidebar-divider my-0">
                </li>

                <!-- Nav Item - Dashboard -->
                <li class="nav-item {% if active_menu == "home" %}active{% endif %}">
                    <a class="nav-link" href="{% url 'viewer:index' %}">
                        <i class="fas fa-fw fa-tachometer-alt"></i>
                        <span>Dashboard</span>
                    </a>
                </li>

                <!-- Divider -->
                <li>
                    <hr class="sidebar-divider">
                </li>

                {% if user.is_authenticated %}
                    <!-- Engine Heading -->
                    <li>
                        <div class="sidebar-heading">
                            Engine
                        </div>
                    </li>

                    <!-- Nav Item - Data Engine -->
                    <li class="nav-item {% if active_menu == "workbench" %}active{% endif %}">
                        <a class="nav-link" href="{% url 'engine:workbench' %}">
                            <i class="fas fa-fw fa-tools"></i>
                            <span>Workbench</span>
                        </a>
                    </li>
                {% endif %}

                <!-- Viewer Heading -->
                <li>
                    <div class="sidebar-heading">
                        Viewer
                    </div>
                </li>

                <!-- Nav Item - Data Engine -->
                <li class="nav-item {% if active_menu == "browser" %}active{% endif %}">
                    <a class="nav-link" href="{% url 'viewer:browser' %}">
                        <i class="fas fa-fw fa-eye"></i>
                        <span>Browser</span>
                    </a>
                </li>

                <!-- Divider -->
                <li>
                    <hr class="sidebar-divider d-none d-md-block">
                </li>

                <!-- Sidebar Toggle (Sidebar) -->
                <li class="text-center">
                    <div class="d-none d-md-inline">
                        <button class="rounded-circle border-0" id="sidebarToggle"></button>
                    </div>
                </li>
            </ul>
            <!-- End of Sidebar -->

            <!-- Content Wrapper -->
            <div id="content-wrapper" class="d-flex flex-column">

                <!-- Main Content -->
                <div id="content">

                    <!-- Top Bar -->
                    <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                        <!-- Sidebar Toggle (Top Bar) -->
                        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                            <i class="fa fa-bars"></i>
                        </button>

                        {% block extra-top-bar-form %}{% endblock %}
                        <ul class="navbar-nav ml-auto">

                            {% if user.is_authenticated %}
                                <!-- Nav Item - User Information -->
                                <li class="nav-item dropdown no-arrow">
                                    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="fas fa-laugh-wink mr-1"></i>
                                        <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.username }}</span>
                                    </a>
                                    <!-- Dropdown - User Information -->
                                    <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                         aria-labelledby="userDropdown">
                                        <a class="dropdown-item" href="{% url 'logout' %}">
                                            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                            Logout
                                        </a>
                                    </div>
                                </li>
                            {% else %}
                                <a class="btn btn-outline-primary btn-sm" href="{% url "login" %}" role="button">Login</a>
                            {% endif %}
                        </ul>

                    </nav>
                    <!-- End of Top Bar -->

                    <!-- Begin Messages -->
                    {% if messages %}
                        <div class="container-fluid">
                            {% for message in messages %}
                                <div class="row">
                                    <div class="col">
                                        <div class="alert alert-{{ message.tags }}">
                                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                                            {{ message }}
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    {% endif %}
                    <!-- End of Messages -->

                    <!-- Begin Page Content -->
                    {% block page_content %}{% endblock %}
                    <!-- End of Page Content -->
                </div>
                <!-- End of Main Content -->

                <!-- Footer -->
                {% comment %} <footer class="sticky-footer bg-white">
                    <div class="container my-auto">
                        <div class="copyright text-center my-auto">
                            <span>Copyright &copy; Data Graph 2020</span>
                        </div>
                    </div>
                </footer> {% endcomment %}
                <!-- End of Footer -->

            </div>
            <!-- End of Content Wrapper -->
        </div>
        <!-- End of Page Wrapper -->

        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top">
            <i class="fas fa-angle-up"></i>
        </a>

        <!-- Google Analytics -->
        <div style="display:none">
            <img src="{% google_analytics %}" width="0" height="0" />
        </div>

        <!-- Bootstrap core JavaScript-->
        <script src="{% static "jquery/js/jquery-3.4.1.min.js" %}" crossorigin="anonymous"></script>
        <script src="{% static "bootstrap/js/bootstrap.bundle.min.js" %}" crossorigin="anonymous"></script>

        <!-- Core plugin JavaScript-->
        <script src="{% static "jquery-easing/js/jquery.easing.min.js" %}"></script>

        <!-- Custom scripts for all pages-->
        <script src="{% static "datagraph/sb-admin-2.bundle.js" %}"></script>

        <!-- Page level custom scripts -->
        {% block extra_js %}{% endblock %}
    </body>
</html>